
contact_links:
  - name: â” Questions / Help
    url: https://botrix.cc/join
    about: Please join our support server if you have any questions in regards to our service that AREN'T bug related.
  - name: ğŸ“ƒ Discord.js Guide
    url: https://discordjs.guide/
    about: The official guide for discord.js
